import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, ArrowDownToLine, ArrowRight, ArrowUp, Box, Check, ChevronRight, CircleHelp, Clock3, Compass, Flag, History, Layers3, RotateCcw, RotateCw, ShieldCheck, Trophy, X } from 'lucide-react';
import { CATALOGUE, definition } from './engine/catalogue';
import { abandon, createGame, customs, gainsForMove, playMove, ranking, tick } from './engine/game';
import { connected, faceAt, groups, initialBoard, top, visible } from './engine/geometry';
import { candidates, evaluateMove } from './engine/moves';
import type { Crate, Direction, Game, Move } from './engine/types';
import { loadGame, saveGame, stageGame } from './storage/save';
import { Board, LABELS, PALETTE, SYMBOLS, type View } from './components/Board';
import { Modal } from './components/Modal';
const faceLabels = ['Dessus', 'Nord', 'Est', 'Sud', 'Ouest', 'Dessous'];
const directions: Direction[] = ['nord', 'est', 'sud', 'ouest'];
function formatTime(ms: number) { const s = Math.max(0, Math.ceil(ms / 1000)); return `${Math.floor(s / 60).toString().padStart(2, '0')}:${(s % 60).toString().padStart(2, '0')}`; }
function moveLabel(m: Move) { return m.kind === 'pivot' ? `Pivot de ${m.quarterTurns * 90}°` : `${m.kind === 'chute' ? 'Chute' : 'Bascule'} vers le ${m.direction}${m.kind === 'chute' && m.quarterTurns ? ` · pivot ${m.quarterTurns * 90}°` : ''}`; }
function FaceChip({ crate, slot }: { crate: Crate; slot: number }) { const face = faceAt(crate, slot); return <div className={`face-chip ${face ? 'colored' : 'neutral'}`} style={face ? { '--face': PALETTE[face] } as React.CSSProperties : undefined}><span>{faceLabels[slot]}</span><strong>{face ? `${SYMBOLS[face]} ${LABELS[face]}` : definition(crate.id).name}</strong><small>Face physique {crate.orientation[slot] + 1}</small></div>; }
const HELPTEXT = [
  ['Le but du jeu', 'Rangez les caisses en groupes visibles d’au moins deux caisses de même couleur supérieure, au même étage, en contact par une face latérale. Le meilleur score gagne. Une couleur sur le dessus n’accorde pas un droit exclusif de déplacement.'],
  ['Un tour, trois mouvements', 'Vous disposez de cinq minutes pour effectuer exactement trois coups puis votre décision Douane. Le premier mouvement de la partie est une chute depuis le sommet. Une déconnexion temporaire est permise, mais toutes les caisses doivent former un seul ensemble connecté par faces au troisième coup.'],
  ['Bascule et chute', 'La bascule roule d’une face vers une case voisine libre, sans diagonale ni montée. Le dessus change. Une descente est une chute : elle conserve le dessus et s’arrête au premier support. Le pivot gratuit de chute tourne autour de Z, sans déplacement horizontal supplémentaire.'],
  ['Pivoter', 'Une caisse au dessus non recouvert peut pivoter sur place, même rangée et en contact latéral, sauf si elle porte la Douane. Un pivot effectif coûte un coup. Un tour complet sans changement ne compte pas.'],
  ['Scores et blocages', 'Le groupe complet rapporte sa taille ×1 au sol, ×3 au milieu, ×5 au sommet. Chaque nouveau rangement marque, y compris une fusion ou un groupe reformé par dévoilement. Le groupe de la caisse déplacée est crédité d’abord, celui dévoilé ensuite. Les couleurs adverses reçoivent leurs points. Une caisse rangée ne peut pas basculer ; un masquage ou une chute peut casser son groupe.'],
  ['La Douane', 'Après les trois coups, placez le jeton sur un dessus accessible ou confirmez son maintien. Le premier placement est obligatoire. La Douane interdit tout mouvement de sa caisse et toute arrivée ou passage au-dessus. Cette décision est comprise dans les cinq minutes.'],
  ['État exact et retour arrière', 'Une caisse ne peut retrouver ses mêmes coordonnées et sa même orientation pendant un tour. Les pivots sont inclus. Un mouvement effectué ne s’annule pas manuellement. La caméra et l’inspection ne sont pas des coups.'],
  ['Temps et abandon', 'Pas de pause. Un tour non terminé après cinq minutes vaut abandon ; une décision à l’échéance exacte est acceptée. L’abandon restaure le plateau et tous les scores du début de tour. Le prochain joueur actif reçoit trois coups et cinq minutes. La couleur abandonnée reste bloquante mais ne marque plus. Le dernier joueur actif gagne.'],
  ['Inspection et fin', 'Tous les joueurs peuvent consulter les six faces des caisses au dessus visible, même pendant le tour adverse. S’il n’existe pas de séquence valide pour terminer les trois coups, la partie finit immédiatement aux scores acquis, sans restauration. Les meilleurs scores à égalité partagent la victoire. Les abandons occupent les dernières places, le premier abandon étant dernier.'],
];
export default function App() {
  const [game, setGame] = useState<Game | null>(null); const gameRef = useRef<Game | null>(null);
  const [loaded, setLoaded] = useState(false); const [count, setCount] = useState(2); const [names, setNames] = useState(['', '', '', '']);
  const [selected, setSelected] = useState<number | null>(null); const [view, setView] = useState<View>('libre');
  const [kind, setKind] = useState<Move['kind']>('chute'); const [turns, setTurns] = useState<0 | 1 | 2 | 3>(0); const [proposal, setProposal] = useState<Move | null>(null);
  const [modal, setModal] = useState<'aide' | 'abandon' | 'nouvelle' | null>(null); const [error, setError] = useState(''); const [saveStatus, setSaveStatus] = useState('');
  const [now, setNow] = useState(Date.now()); const [reduced, setReduced] = useState(() => matchMedia('(prefers-reduced-motion: reduce)').matches);
  const [canEdit, setCanEdit] = useState(false); const lockRelease = useRef<(() => void) | null>(null); const mounted = useRef(true); const writes = useRef(Promise.resolve());
  const commit = useCallback((next: Game) => {
    const staged = stageGame(next);
    setSaveStatus(staged ? 'Sauvegarde en cours…' : 'Sauvegarde de secours indisponible…');
    gameRef.current = next; setGame(next);
    writes.current = writes.current.then(() => saveGame(next)).then(() => { if (mounted.current) setSaveStatus('Partie sauvegardée sur cet appareil'); }).catch(() => { if (mounted.current) setSaveStatus('Sauvegarde indisponible : gardez cet onglet ouvert.'); });
  }, []);
  useEffect(() => {
    mounted.current = true;
    let cancelled = false;
    async function start() {
      try { const saved = await loadGame(); if (!cancelled) { gameRef.current = saved; setGame(saved); } }
      catch (e) { if (!cancelled) setError((e as Error).message); }
      if (!cancelled) setLoaded(true);
    }
    if (navigator.locks) {
      void navigator.locks.request('dockers-partie-locale', { ifAvailable: true }, async lock => {
        if (!lock) { if (!cancelled) { setError('La partie est déjà ouverte dans un autre onglet. Fermez cet onglet puis rechargez ici pour jouer.'); setLoaded(true); } return; }
        if (cancelled) return;
        setCanEdit(true); await start();
        await new Promise<void>(resolve => { lockRelease.current = resolve; if (cancelled) resolve(); });
      });
    } else { setCanEdit(true); void start(); }
    return () => { cancelled = true; mounted.current = false; lockRelease.current?.(); };
  }, []);
  useEffect(() => { if (!canEdit || !loaded) return; const timer = window.setInterval(() => { const time = Date.now(); setNow(time); const current = gameRef.current; if (current) { const next = tick(current, time); if (next !== current) { setProposal(null); setSelected(null); setModal(null); commit(next); } } }, 200); return () => clearInterval(timer); }, [canEdit, loaded, commit]);
  const board = game?.board ?? initialBoard(); const crate = board.find(c => c.id === selected);
  const current = game?.players[game.activePlayer]; const finished = game?.phase === 'terminée';
  const allGroups = useMemo(() => groups(board), [board]); const selectedGroup = allGroups.find(g => g.ids.includes(selected ?? 0));
  const available = useMemo(() => game && game.phase === 'mouvements' && selected ? candidates(game, selected) : [], [game, selected]);
  const preview = game && proposal ? evaluateMove(game, proposal) : null;
  const previewGains = game && proposal && preview?.ok ? gainsForMove(game, { ...game, board: preview.board! }, proposal) : [];
  const select = (id: number) => { setSelected(id || null); setProposal(null); setError(''); };
  function act(operation: (g: Game) => Game) { const latest = gameRef.current; if (!latest || !canEdit) return; try { commit(operation(latest)); setProposal(null); setError(''); } catch (e) { setError((e as Error).message); } }
  function begin() { try { commit(createGame(names.slice(0, count))); setSelected(null); setModal(null); setError(''); setNow(Date.now()); } catch (e) { setError((e as Error).message); } }
  const status = crate ? !visible(board, crate) ? 'Surmontée · immobile' : game?.customsId === crate.id ? 'Sous Douane · immobile' : selectedGroup ? 'Rangée · pivot possible' : 'Disponible' : '';
  return <div className="app-shell">
    <header className="app-header"><a className="brand" href={import.meta.env.BASE_URL} onClick={e => { if (game && !finished) e.preventDefault(); }} aria-label="DOCKERS"><span className="brand-icon"><Box size={27} strokeWidth={1.5} /></span><span>DOCKERS<small>LE JEU QUI MUSCLE LE CERVEAU</small></span></a><nav><span className="local-badge"><span /> Partie locale · Français</span><button className="text-button" onClick={() => setModal('aide')}><CircleHelp size={18} /> Les règles</button>{game && <button className="text-button" onClick={() => setModal('nouvelle')}>Nouvelle partie <ArrowRight size={16} /></button>}</nav></header>
    {error && <div className="notice error" role="alert">{error}<button onClick={() => setError('')} aria-label="Fermer le message"><X size={16} /></button></div>}
    {!loaded ? <div className="loading">Ouverture de l’entrepôt…</div> : !game ? <main className="welcome">
      <section className="welcome-copy"><div className="eyebrow"><span className="short-line" /> BIENVENUE SUR LES QUAIS</div><h1>Un entrepôt.<br />27 caisses.<br /><em>À vous de jouer.</em></h1><p>Faites basculer les caisses, rangez vos couleurs et gardez un coup d’avance. Une affaire de stratégie, sous tous les angles.</p><div className="welcome-facts"><span><Box size={18} /> 27 caisses</span><span><Layers3 size={18} /> 3 étages</span><span><Clock3 size={18} /> 5 min / tour</span></div>
        <form className="setup" onSubmit={e => { e.preventDefault(); begin(); }}><div className="setup-head"><h2>Qui embarque ?</h2><span>2 À 4 JOUEURS</span></div><div className="segmented count-picker" aria-label="Nombre de joueurs">{[2, 3, 4].map(n => <button type="button" key={n} className={count === n ? 'active' : ''} onClick={() => setCount(n)} aria-pressed={count === n}>{n} joueurs</button>)}</div><div className="name-fields">{Array.from({ length: count }, (_, i) => <label key={i}><span>Docker {i + 1}</span><input aria-label={`Nom du joueur ${i + 1}`} maxLength={30} placeholder={`Docker ${i + 1}`} value={names[i]} onChange={e => setNames(names.map((n, j) => i === j ? e.target.value : n))} /></label>)}</div><button className="primary launch" disabled={!canEdit} type="submit">Commencer la partie <ArrowRight size={20} /></button><p className="setup-note">Les couleurs et le premier joueur sont tirés au sort.<br />Un appareil partagé. Aucun compte nécessaire.</p></form>
      </section><section className="welcome-board"><div className="board-kicker"><span>01 / L’ENTREPÔT</span><span>OBSERVEZ SOUS TOUS LES ANGLES</span></div><div className="welcome-canvas"><Board board={board} selected={selected} onSelect={select} view="libre" reduced={reduced} /></div><div className="welcome-caption"><Compass size={22} /><p><strong>Tout commence ici.</strong><br />Tournez le plateau pour explorer les caisses.</p><span>3 × 3 × 3</span></div><div className="welcome-footnote">LE DESSUS CHANGE. LA STRATÉGIE AUSSI.</div></section>
    </main> : <main className="game-layout">
      {!finished && <div className="turn-mini"><span>{current!.name} · {game.movesMade}/3 coups{game.phase === 'douane' ? ' · Douane' : ''}</span><strong>{formatTime(game.deadline - now)}</strong></div>}
      <aside className="game-sidebar"><div className="eyebrow">{finished ? 'PARTIE TERMINÉE' : `TOUR ${game.turn.toString().padStart(2, '0')}`}<span className="small-pill">{game.players.filter(p => p.abandonedAt === null).length} EN LICE</span></div>
        <div className="active-player"><span className="color-mark" style={{ background: PALETTE[current!.color] }}>{SYMBOLS[current!.color]}</span><div><span>{finished ? 'DERNIER TOUR' : 'À VOUS DE JOUER'}</span><h1>{current!.name}</h1><p>Compagnie {LABELS[current!.color].toLowerCase()}</p></div></div>
        {!finished && <><div className={`timer ${game.deadline - now <= 60_000 ? 'urgent' : ''}`} role="timer" aria-label={`Temps restant : ${formatTime(game.deadline - now)}`}><div><Clock3 size={17} /><span>TEMPS RESTANT</span></div><strong>{formatTime(game.deadline - now)}</strong><div className="time-track"><i style={{ width: `${Math.max(0, Math.min(100, (game.deadline - now) / 3000))}%` }} /></div><small>Trois coups + Douane. Aucune pause.</small></div><div className="turn-steps">{[0, 1, 2].map(i => <span key={i} className={i < game.movesMade ? 'done' : i === game.movesMade ? 'current' : ''}>{i < game.movesMade ? <Check size={14} /> : i + 1}</span>)}<i /><span className={game.phase === 'douane' ? 'current' : ''}><ShieldCheck size={16} /></span></div><p className="turn-instruction">{game.phase === 'douane' ? <><strong>La Douane, à vous de décider.</strong>Choisissez une caisse au dessus visible{game.customsId ? ' ou conservez le jeton en place.' : '. Le premier placement est obligatoire.'}</> : !game.opened ? <><strong>Ouvrez l’entrepôt.</strong>Faites chuter une caisse du sommet pour créer un espace libre.</> : <><strong>{3 - game.movesMade} mouvement{3 - game.movesMade > 1 ? 's' : ''} à effectuer.</strong>Sélectionnez une caisse et choisissez votre prochain coup.</>}</p></>}
        <div className="scores"><div className="section-label"><span>LES COMPAGNIES</span><Trophy size={15} /></div>{game.players.map(p => <div key={p.id} className={`score-row ${p.id === game.activePlayer && !finished ? 'active' : ''} ${p.abandonedAt !== null ? 'departed' : ''}`}><span className="score-dot" style={{ background: PALETTE[p.color] }}>{SYMBOLS[p.color]}</span><div><strong>{p.name}</strong><small>{p.abandonedAt ? 'A abandonné' : LABELS[p.color]}</small></div><b>{p.score}<small>PTS</small></b></div>)}</div>
        {!finished && <button className="abandon-button" onClick={() => setModal('abandon')}><Flag size={15} /> Abandonner la partie</button>}<p className="save-status" role="status">{saveStatus || 'Sauvegarde automatique locale'}</p>
      </aside>
      <section className="board-section"><div className="board-top"><div><div className="eyebrow">LE PLATEAU</div><h2>L’entrepôt <span>7 × 7</span></h2></div><div className="board-info"><span><i className="ring-symbol" /> Groupe rangé</span><span><ShieldCheck size={14} /> Douane</span></div></div>
        <div className="board-stage"><Board game={game} board={board} selected={selected} onSelect={select} view={view} reduced={reduced} /><div className="compass-label"><span>N</span><ArrowUp size={15} /><small>VUE DE RÉFÉRENCE</small></div>{!connected(board) && <div className="board-notice">Caisses séparées · reconnectez-les avant le troisième coup</div>}<div className="board-caption">{view === 'libre' ? 'Glissez pour tourner · Molette ou pincement pour zoomer' : 'Vue fixe · Molette ou pincement pour zoomer'}</div></div>
        <div className="view-bar"><div className="segmented">{([['libre', '3D libre'], ['dessus', 'Dessus'], ['nord', 'Nord'], ['est', 'Est'], ['sud', 'Sud'], ['ouest', 'Ouest']] as [View, string][]).map(([v, label]) => <button key={v} onClick={() => setView(v)} aria-pressed={view === v} className={view === v ? 'active' : ''}>{v === 'libre' && <Compass size={15} />}{label}</button>)}</div><label className="reduce-motion"><input type="checkbox" checked={reduced} onChange={e => setReduced(e.target.checked)} />Animations réduites</label></div>
        <details className="crate-list"><summary><Layers3 size={16} /> Liste accessible des 27 caisses <ChevronRight size={16} /></summary><div className="crate-list-grid">{board.map(c => <button key={c.id} onClick={() => select(c.id)} className={selected === c.id ? 'selected' : ''} aria-pressed={selected === c.id}><span>{String(c.id).padStart(2, '0')}</span>{definition(c.id).name}<small>{c.z === 0 ? 'Sol' : `Étage ${c.z}`} · {visible(board, c) ? top(c) ? LABELS[top(c)!] : 'Neutre' : 'Surmontée'}</small></button>)}</div></details>
        <details className="journal"><summary><History size={16} /> Journal de la partie <span>{game.events.length} événements</span><ChevronRight size={16} /></summary><ol>{[...game.events].reverse().map(e => <li key={e.id} className={e.reverted ? 'reverted' : ''}><span>TOUR {e.turn} · {game.players[e.playerId].name}</span><p>{e.text}{e.reverted && <strong> — Annulé après abandon</strong>}</p>{e.gains?.map((gain, i) => <small key={i}>{game.players[gain.playerId].name} +{gain.points} pts · {gain.size} caisses ×{gain.multiplier} · {gain.trigger}</small>)}</li>)}</ol></details>
      </section>
      <aside className="crate-panel">
        {finished ? <div className="results"><div className="result-icon"><Trophy size={34} /></div><div className="eyebrow">DÉCOMPTE FINAL</div><h2>{game.result!.winners.length > 1 ? 'Victoire partagée !' : `${game.players[game.result!.winners[0]].name} gagne !`}</h2><p>{game.result!.reason}</p><ol>{ranking(game).map(({ player: p, rank }) => <li key={p.id}><b>{rank}</b><span>{p.name}<small>{p.abandonedAt ? 'Abandon · hors victoire' : 'En lice'}</small></span><strong>{p.score}<small>pts</small></strong></li>)}</ol><button className="primary" onClick={() => setModal('nouvelle')}>Rejouer <ArrowRight size={18} /></button></div> : !crate ? <div className="empty-selection"><div className="selection-icon"><Box size={36} strokeWidth={1} /></div><div className="eyebrow">VOTRE PROCHAIN COUP</div><h2>Chaque caisse<br />a son potentiel.</h2><p>Sélectionnez une caisse sur le plateau pour inspecter ses six faces et préparer votre mouvement.</p><span className="small-rule" /><p className="muted">Vous pouvez aussi utiliser la liste des caisses sous le plateau.</p></div> : <>
          <div className="crate-title"><div><span className="eyebrow">CAISSE {String(crate.id).padStart(2, '0')}</span><h2>{definition(crate.id).name}</h2></div><button className="icon-button" onClick={() => select(0)} aria-label="Désélectionner la caisse"><X size={18} /></button></div><div className="crate-meta"><span>{crate.z === 0 ? 'Sol' : `Étage ${crate.z}`}</span><span>X {crate.x} · Y {crate.y}</span></div><p className={`crate-status ${game.customsId === crate.id ? 'protected' : ''}`}>{game.customsId === crate.id ? <ShieldCheck size={15} /> : <Box size={15} />}{status}</p>
          <div className="section-label"><span>LES SIX FACES</span><span>CONSULTATION LIBRE</span></div><div className="face-grid">{faceLabels.map((_, i) => <FaceChip key={i} crate={crate} slot={i} />)}</div><p className="inspection-note">Inspecter ne consomme aucun coup.</p>
          {game.phase === 'douane' ? <div className="customs-actions"><h3>Terminer le tour</h3><p>La décision Douane doit être effectuée avant la fin du décompte.</p><button className="primary" disabled={!visible(board, crate)} onClick={() => act(g => customs(g, crate.id))}><ShieldCheck size={18} />{crate.id === game.customsId ? 'Conserver la Douane ici' : 'Placer la Douane ici'}</button>{!visible(board, crate) && <p className="muted">Cette caisse est recouverte : choisissez un dessus accessible.</p>}{game.customsId !== null && crate.id !== game.customsId && <button className="secondary" onClick={() => act(g => customs(g, null))}>Conserver la Douane en place</button>}</div> : <div className="move-editor"><div className="section-label"><span>CHOISIR UN MOUVEMENT</span><span>1 COUP</span></div><div className="move-tabs">{([['chute', ArrowDownToLine, 'Chuter'], ['bascule', RotateCw, 'Basculer'], ['pivot', RotateCcw, 'Pivoter']] as const).map(([k, Icon, label]) => <button key={k} className={kind === k ? 'active' : ''} onClick={() => { setKind(k); setProposal(null); }} aria-pressed={kind === k}><Icon size={18} />{label}</button>)}</div>
          {kind === 'chute' && <label className="pivot-select">Pivot gratuit à l’arrivée<select aria-label="Pivot gratuit de chute" value={turns} onChange={e => { setTurns(Number(e.target.value) as typeof turns); setProposal(null); }}><option value={0}>Sans pivot</option><option value={1}>90° horaire</option><option value={2}>180°</option><option value={3}>270° horaire</option></select></label>}
          <div className="move-options">{kind === 'pivot' ? ([1, 2, 3] as const).map(t => { const move: Move = { kind: 'pivot', crateId: crate.id, quarterTurns: t }; const result = evaluateMove(game, move); return <button key={t} disabled={!result.ok} title={result.reason} onClick={() => setProposal(move)} className={proposal?.kind === 'pivot' && proposal.quarterTurns === t ? 'selected' : ''}>{t * 90}°</button>; }) : directions.map(direction => { const move: Move = kind === 'chute' ? { kind, crateId: crate.id, direction, quarterTurns: turns } : { kind: 'bascule', crateId: crate.id, direction }; const result = evaluateMove(game, move); return <button key={direction} aria-label={direction[0].toUpperCase() + direction.slice(1)} disabled={!result.ok} title={result.reason} onClick={() => setProposal(move)} className={proposal?.kind !== 'pivot' && proposal?.direction === direction ? 'selected' : ''}><span>{direction === 'nord' ? '↑' : direction === 'sud' ? '↓' : direction === 'est' ? '→' : '←'}</span>{direction[0].toUpperCase() + direction.slice(1)}</button>; })}</div>
          {!available.some(m => m.kind === kind) && <p className="action-explanation">{evaluateMove(game, kind === 'pivot' ? { kind, crateId: crate.id, quarterTurns: 1 } : kind === 'chute' ? { kind, crateId: crate.id, direction: 'nord', quarterTurns: turns } : { kind, crateId: crate.id, direction: 'nord' }).reason || 'Aucune destination autorisée pour ce mouvement.'}</p>}
          {proposal && preview?.ok && <div className="preview" aria-live="polite"><strong>{moveLabel(proposal)}</strong><span>Arrivée : X {preview.moved!.x} · Y {preview.moved!.y} · {preview.moved!.z === 0 ? 'Sol' : `Étage ${preview.moved!.z}`}</span><span>Dessus : {top(preview.moved!) ? LABELS[top(preview.moved!)!] : 'Neutre'}</span>{previewGains.map((gain, i) => <b key={i}>+{gain.points} pts pour {game.players[gain.playerId].name} · {gain.trigger}</b>)}<button className="primary" onClick={() => act(g => playMove(g, proposal))}>Effectuer {proposal.kind === 'pivot' ? 'le pivot' : proposal.kind === 'chute' ? 'la chute' : 'la bascule'} <ArrowRight size={17} /></button><small>Un coup effectué ne peut pas être annulé.</small></div>}
          </div>}
        </>}
        {!finished && game.phase === 'douane' && !crate && game.customsId !== null && <button className="primary" onClick={() => act(g => customs(g, null))}>Conserver la Douane en place</button>}
      </aside>
    </main>}
    <footer className="app-footer"><span>DOCKERS <i>·</i> Un jeu de Philippe Leurquin</span><span>Observez. Anticipez. Rangez.</span><span>{game ? 'LOCAL · SAUVEGARDE SUR CET APPAREIL' : '2–4 JOUEURS · SUR UN APPAREIL PARTAGÉ'}</span></footer>
    {modal === 'aide' && <Modal title="Les règles de DOCKERS" onClose={() => setModal(null)}><div className="help-intro">Une partie locale, en trois dimensions. Les règles ci-dessous intègrent les décisions de l’auteur du projet.</div><div className="help-content">{HELPTEXT.map(([title, text], i) => <section key={title}><span>{String(i + 1).padStart(2, '0')}</span><div><h3>{title}</h3><p>{text}</p></div></section>)}</div><button className="primary" onClick={() => setModal(null)}>Compris, à moi de jouer <Check size={18} /></button></Modal>}
    {modal === 'abandon' && <Modal title="Abandonner ce tour ?" onClose={() => setModal(null)}><p>Le plateau et tous les scores seront restaurés à leur état de début de tour. {current?.name} ne pourra plus gagner cette partie. Les autres joueurs continueront, ou le dernier joueur remportera la victoire.</p><div className="modal-actions"><button className="secondary" onClick={() => setModal(null)}>Continuer à jouer</button><button className="danger" onClick={() => { act(g => abandon(g)); setModal(null); select(0); }}>Confirmer l’abandon</button></div><small>Le chronomètre continue pendant cette confirmation.</small></Modal>}
    {modal === 'nouvelle' && <Modal title="Une nouvelle partie ?" onClose={() => setModal(null)}><p>{finished ? 'Le résultat de cette partie sera archivé sur cet appareil.' : 'La partie actuelle sera archivée. Cette action lance une nouvelle configuration ; elle ne met pas la partie en pause.'}</p><div className="modal-actions"><button className="secondary" onClick={() => setModal(null)}>Revenir</button><button className="primary" onClick={() => { if (game && !finished) { setError('Terminez la partie ou abandonnez avant d’en commencer une nouvelle.'); setModal(null); return; } setGame(null); gameRef.current = null; select(0); setModal(null); }}>Préparer une partie <ArrowRight size={16} /></button></div></Modal>}
  </div>;
}
